# Stage 1: Build React app
FROM node:20-alpine

WORKDIR /app

# Copy only the package files first for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3000 to serve the app
EXPOSE 3000

CMD ["npm","run","dev"]
