# Stage 1: Build React app
FROM node:18-alpine

WORKDIR /app

# Copy only the package files first for dependency installation
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . . 

# Expose port 80 to serve the app
EXPOSE 80

CMD ["npm","run","dev"]